In [55]:
import pandas as pd
import numpy as np
import requests
import gzip
import io
import pandas as pd
import numpy as np
import requests
import gzip
from io import StringIO
import matplotlib.pyplot as plt
import seaborn as sns
import os

os.chdir("/beegfs/scratch/ric.broccoli/kubacki.michal/SRF_SRRM3_Tasic")

In [7]:
def download_data(url):
    response = requests.get(url)
    # Create a BytesIO object from the response content
    bytes_io = io.BytesIO(response.content)
    # Open with gzip
    with gzip.GzipFile(fileobj=bytes_io) as gz:
        # Decode bytes to string
        content = gz.read().decode('utf-8')
        # Read CSV from string
        return pd.read_csv(io.StringIO(content))

In [8]:
# Download URLs
rpkm_url = "https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE71585&format=file&file=GSE71585%5FRefSeq%5FRPKM%2Ecsv%2Egz"
counts_url = "https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE71585&format=file&file=GSE71585%5FRefSeq%5Fcounts%2Ecsv%2Egz"

In [11]:
try:
    # Load RPKM and counts data
    rpkm_data = download_data(rpkm_url)
    counts_data = download_data(counts_url)
    
    print("Data downloaded successfully!")
    print("RPKM data shape:", rpkm_data.shape)
    print("Counts data shape:", counts_data.shape)
    
except Exception as e:
    print("Error downloading data:", str(e))

Data downloaded successfully!
RPKM data shape: (24057, 1810)
Counts data shape: (24057, 1810)

In [27]:
rpkm_data.head(3)

,gene,Calb2_tdTpositive_cell_1,Calb2_tdTpositive_cell_2,Calb2_tdTpositive_cell_3,Calb2_tdTpositive_cell_4,Calb2_tdTpositive_cell_5,Calb2_tdTpositive_cell_6,Calb2_tdTpositive_cell_7,Calb2_tdTpositive_cell_8,Calb2_tdTpositive_cell_9,...,CAV_VISp_Contra_tdTpos_cell_5,Rbp4_CTX_10pg_1,Rbp4_CTX_10pg_2,Rbp4_CTX_10pg_3,Rbp4_CTX_10pg_4,Rbp4_CTX_10pg_5,Rbp4_CTX_10pg_6,Rbp4_CTX_250ng_1,Rbp4_CTX_250ng_2,Trib2_CTX_250ng_1
0,0610005C13Rik,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.29,0.31,0.18
1,0610007C21Rik,76.13,512.73,172.75,170.56,113.87,10.90,191.23,67.41,70.56,...,92.20,31.56,62.69,113.11,288.28,40.88,153.99,40.02,42.15,40.63
2,0610007L01Rik,0.05,10.11,0.00,0.02,0.04,0.06,70.19,1.82,0.00,...,24.45,4.85,0.01,1.36,0.00,1.10,1.06,13.32,13.78,12.56

In [28]:
rpkm_data = rpkm_data.set_index('gene')
rpkm_data.head(3)

,Calb2_tdTpositive_cell_1,Calb2_tdTpositive_cell_2,Calb2_tdTpositive_cell_3,Calb2_tdTpositive_cell_4,Calb2_tdTpositive_cell_5,Calb2_tdTpositive_cell_6,Calb2_tdTpositive_cell_7,Calb2_tdTpositive_cell_8,Calb2_tdTpositive_cell_9,Calb2_tdTpositive_cell_10,...,CAV_VISp_Contra_tdTpos_cell_5,Rbp4_CTX_10pg_1,Rbp4_CTX_10pg_2,Rbp4_CTX_10pg_3,Rbp4_CTX_10pg_4,Rbp4_CTX_10pg_5,Rbp4_CTX_10pg_6,Rbp4_CTX_250ng_1,Rbp4_CTX_250ng_2,Trib2_CTX_250ng_1
gene,,,,,,,,,,,,,,,,,,,,,
0610005C13Rik,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.29,0.31,0.18
0610007C21Rik,76.13,512.73,172.75,170.56,113.87,10.90,191.23,67.41,70.56,73.35,...,92.20,31.56,62.69,113.11,288.28,40.88,153.99,40.02,42.15,40.63
0610007L01Rik,0.05,10.11,0.00,0.02,0.04,0.06,70.19,1.82,0.00,20.88,...,24.45,4.85,0.01,1.36,0.00,1.10,1.06,13.32,13.78,12.56

In [29]:
counts_data.head(3)

,gene,Calb2_tdTpositive_cell_1,Calb2_tdTpositive_cell_2,Calb2_tdTpositive_cell_3,Calb2_tdTpositive_cell_4,Calb2_tdTpositive_cell_5,Calb2_tdTpositive_cell_6,Calb2_tdTpositive_cell_7,Calb2_tdTpositive_cell_8,Calb2_tdTpositive_cell_9,...,CAV_VISp_Contra_tdTpos_cell_5,Rbp4_CTX_10pg_1,Rbp4_CTX_10pg_2,Rbp4_CTX_10pg_3,Rbp4_CTX_10pg_4,Rbp4_CTX_10pg_5,Rbp4_CTX_10pg_6,Rbp4_CTX_250ng_1,Rbp4_CTX_250ng_2,Trib2_CTX_250ng_1
0,0610005C13Rik,0.00,0.00,0.00,0.0,0.0,0.00,0.00,0.0,0.0,...,0.00,0.0,0.00,0.0,0.0,0.00,0.00,8.0,9.00,5.00
1,0610007C21Rik,992.00,2287.02,491.78,1932.0,1425.0,130.03,2110.02,955.0,326.0,...,352.06,401.0,1750.99,1463.0,3439.0,502.95,1486.36,956.4,1054.94,944.03
2,0610007L01Rik,2.57,177.00,0.00,1.0,2.0,3.00,3040.99,101.0,0.0,...,367.00,242.0,1.00,69.0,0.0,53.00,40.15,1251.0,1356.20,1147.00

In [30]:
counts_data = counts_data.set_index('gene')
counts_data.head(3)

,Calb2_tdTpositive_cell_1,Calb2_tdTpositive_cell_2,Calb2_tdTpositive_cell_3,Calb2_tdTpositive_cell_4,Calb2_tdTpositive_cell_5,Calb2_tdTpositive_cell_6,Calb2_tdTpositive_cell_7,Calb2_tdTpositive_cell_8,Calb2_tdTpositive_cell_9,Calb2_tdTpositive_cell_10,...,CAV_VISp_Contra_tdTpos_cell_5,Rbp4_CTX_10pg_1,Rbp4_CTX_10pg_2,Rbp4_CTX_10pg_3,Rbp4_CTX_10pg_4,Rbp4_CTX_10pg_5,Rbp4_CTX_10pg_6,Rbp4_CTX_250ng_1,Rbp4_CTX_250ng_2,Trib2_CTX_250ng_1
gene,,,,,,,,,,,,,,,,,,,,,
0610005C13Rik,0.00,0.00,0.00,0.0,0.0,0.00,0.00,0.0,0.0,0.0,...,0.00,0.0,0.00,0.0,0.0,0.00,0.00,8.0,9.00,5.00
0610007C21Rik,992.00,2287.02,491.78,1932.0,1425.0,130.03,2110.02,955.0,326.0,933.0,...,352.06,401.0,1750.99,1463.0,3439.0,502.95,1486.36,956.4,1054.94,944.03
0610007L01Rik,2.57,177.00,0.00,1.0,2.0,3.00,3040.99,101.0,0.0,1042.0,...,367.00,242.0,1.00,69.0,0.0,53.00,40.15,1251.0,1356.20,1147.00

In [37]:
def analyze_srrm(df):
    if not df.index.dtype == 'object':
        df.index = df.index.astype(str)
    srrm3_data = df[df.index.str.contains('Srrm', case=False)]
    return srrm3_data

# Ensure index is string type before analysis
rpkm_data.index = rpkm_data.index.astype(str)
counts_data.index = counts_data.index.astype(str)

In [38]:
# Analyze expression patterns
srrm_rpkm = analyze_srrm(rpkm_data)
srrm_counts = analyze_srrm(counts_data)

In [39]:
srrm_rpkm

,Calb2_tdTpositive_cell_1,Calb2_tdTpositive_cell_2,Calb2_tdTpositive_cell_3,Calb2_tdTpositive_cell_4,Calb2_tdTpositive_cell_5,Calb2_tdTpositive_cell_6,Calb2_tdTpositive_cell_7,Calb2_tdTpositive_cell_8,Calb2_tdTpositive_cell_9,Calb2_tdTpositive_cell_10,...,CAV_VISp_Contra_tdTpos_cell_5,Rbp4_CTX_10pg_1,Rbp4_CTX_10pg_2,Rbp4_CTX_10pg_3,Rbp4_CTX_10pg_4,Rbp4_CTX_10pg_5,Rbp4_CTX_10pg_6,Rbp4_CTX_250ng_1,Rbp4_CTX_250ng_2,Trib2_CTX_250ng_1
gene,,,,,,,,,,,,,,,,,,,,,
Srrm1,5.58,8.00,0.17,34.06,19.86,15.55,62.25,13.02,8.52,14.21,...,17.64,3.19,28.30,15.84,21.28,12.31,24.62,33.13,34.16,36.24
Srrm2,5.42,9.82,30.70,22.04,8.20,3.10,41.96,12.93,8.48,10.91,...,14.30,7.96,6.08,33.40,13.60,31.22,8.58,93.60,82.31,100.00
Srrm3,0.04,0.00,0.00,0.00,0.00,0.00,0.00,0.02,0.00,0.53,...,0.00,0.00,0.00,0.00,0.43,0.00,1.91,13.47,14.65,14.50
Srrm4,0.02,0.00,0.00,8.13,2.94,0.00,1.96,1.22,6.18,1.42,...,3.48,1.28,9.34,0.03,0.00,0.02,0.61,7.21,8.14,8.07

In [40]:
srrm_counts

,Calb2_tdTpositive_cell_1,Calb2_tdTpositive_cell_2,Calb2_tdTpositive_cell_3,Calb2_tdTpositive_cell_4,Calb2_tdTpositive_cell_5,Calb2_tdTpositive_cell_6,Calb2_tdTpositive_cell_7,Calb2_tdTpositive_cell_8,Calb2_tdTpositive_cell_9,Calb2_tdTpositive_cell_10,...,CAV_VISp_Contra_tdTpos_cell_5,Rbp4_CTX_10pg_1,Rbp4_CTX_10pg_2,Rbp4_CTX_10pg_3,Rbp4_CTX_10pg_4,Rbp4_CTX_10pg_5,Rbp4_CTX_10pg_6,Rbp4_CTX_250ng_1,Rbp4_CTX_250ng_2,Trib2_CTX_250ng_1
gene,,,,,,,,,,,,,,,,,,,,,
Srrm1,294.34,144.98,2.0,1568.26,1010.00,750.94,2791.68,746.72,160.00,731.38,...,273.03,165.00,3214.73,833.10,1030.00,614.00,964.82,3165.94,3418.05,3366.29
Srrm2,667.00,414.02,826.0,2359.42,969.21,349.00,4374.77,1730.95,370.02,1310.69,...,516.42,955.94,1605.07,4084.54,1529.29,3619.31,781.97,20732.29,19091.81,21530.76
Srrm3,2.00,0.00,0.0,0.00,0.00,0.00,0.00,1.00,0.00,28.99,...,0.00,0.00,0.00,0.00,22.01,0.00,79.00,1357.13,1545.67,1420.17
Srrm4,2.00,0.00,0.0,756.00,301.94,0.00,177.00,142.00,234.08,147.98,...,109.00,133.99,2141.95,3.00,0.00,2.00,48.00,1387.32,1640.75,1508.74

In [43]:
srrm3_rpkm = srrm_rpkm.loc["Srrm3"]
srrm3_counts = srrm_counts.loc["Srrm3"]

In [44]:
# Function to visualize expression patterns
def plot_srrm3_expression(data, title):
    plt.figure(figsize=(15, 6))
    sns.boxplot(data=data.T)
    plt.title(f'Srrm3 Isoform Expression - {title}')
    plt.xticks(rotation=45)
    plt.ylabel('Expression Level')
    plt.tight_layout()
    return plt

In [58]:
# Export results
srrm_rpkm.to_csv('./data_2/srrm_rpkm_data.csv')
srrm_counts.to_csv('./data_2/srrm_counts_data.csv')

In [ ]:
# mamba config --env --append channels conda-forge
# mamba config --env --append channels bioconda
# mamba install --yes -c chaolinzhanglab quantas

In [ ]:
# For Tasic 2018 (SRP150473)
wget -O tasic2018_metadata.tsv "https://www.ebi.ac.uk/ena/portal/api/filereport?accession=SRP150473&result=read_run&fields=run_accession,fastq_ftp,fastq_md5&format=tsv&download=true"

# Extract SRR numbers and create download commands, checking for existing files
cat tasic2018_metadata.tsv | tail -n +2 | while IFS=$'\t' read -r run_acc fastq_urls md5s; do
    IFS=';' read -ra urls <<< "$fastq_urls"
    IFS=';' read -ra checksums <<< "$md5s"
    
    for i in "${!urls[@]}"; do
        url="${urls[$i]}"
        md5="${checksums[$i]}"
        filename=$(basename "$url")
        
        # Check if file exists and has correct MD5
        if [ -f "$filename" ]; then
            existing_md5=$(md5sum "$filename" | cut -d' ' -f1)
            if [ "$existing_md5" = "$md5" ]; then
                echo "# Skipping $filename - already exists with correct MD5" >&2
                continue
            else
                echo "# $filename exists but MD5 mismatch - will redownload" >&2
            fi
        fi
        echo "wget -c 'ftp://$url'"
    done
done > download_commands.sh

chmod +x download_commands.sh

parallel -j 32 < download_commands_2016.sh

In [ ]:
# Same for Tasic 2016 (SRP061902)
wget -O tasic2016_metadata.tsv "https://www.ebi.ac.uk/ena/portal/api/filereport?accession=SRP061902&result=read_run&fields=run_accession,fastq_ftp&format=tsv&download=true"

# Extract SRR numbers and create download commands, checking for existing files
cat tasic2016_metadata.tsv | tail -n +2 | while IFS=$'\t' read -r run_acc fastq_urls md5s; do
    IFS=';' read -ra urls <<< "$fastq_urls"
    IFS=';' read -ra checksums <<< "$md5s"
    
    for i in "${!urls[@]}"; do
        url="${urls[$i]}"
        md5="${checksums[$i]}"
        filename=$(basename "$url")
        
        # Check if file exists and has correct MD5
        if [ -f "$filename" ]; then
            existing_md5=$(md5sum "$filename" | cut -d' ' -f1)
            if [ "$existing_md5" = "$md5" ]; then
                echo "# Skipping $filename - already exists with correct MD5" >&2
                continue
            else
                echo "# $filename exists but MD5 mismatch - will redownload" >&2
            fi
        fi
        echo "wget -c 'ftp://$url'"
    done
done > download_commands_2016.sh

chmod +x download_commands_2016.sh

parallel -j 32 < download_commands_2016.sh